### ISSUE TITLE
Website Discrepancy 

### ISSUE THREAD

**Issue by Rocart03** [worldbank/data-good-training#10]
Depending on what website you access.
example 1:  https://datapartnership.org/gaza-israel-conflict-impact-analysis/notebooks/nighttime-lights/nighttime-lights.html
example 2: https://worldbank.github.io/data-good-training/notebooks/nighttime-lights/nighttime-lights.html
- Each repository has a different amount of data in it as far as MB and the wording is different.

**Comment by g4brielvs** [comment]
@Rocart03 Thank you opening this issue. Please note that a copy of the notebook (example 2) is included in [training](https://worldbank.github.io/data-good-training/README.html). The original notebook (example 1) is part of [another repository](https://datapartnership.org/gaza-israel-conflict-impact-analysis). Please see #8.
