### ISSUE TITLE
Issue on page /notebooks/nighttime-lights/nighttime-lights.html

### ISSUE THREAD

**Issue by cperrin2** [worldbank/data-good-training#6]
Under the Point-in-Time Comparison heading, the 'Daily' comparison between Jan. 1, 2023 and Oct. 21, 2023 is not loading properly and showing up blank on the page. 

<img width="526" alt="Screenshot 2024-03-03 205048" src="https://github.com/worldbank/data-good-training/assets/159584754/4943c5f8-77f9-4d89-84c0-c1d167ff558e">

**Comment by g4brielvs** [comment]
@cperrin2 Thank you for reporting this issue. The images are available on the original repository at https://datapartnership.org/gaza-israel-conflict-impact-analysis/notebooks/nighttime-lights/nighttime-lights.html#point-in-time-comparison.
