### ISSUE TITLE
Two Different Github Pages

### ISSUE THREAD

**Issue by kholeigh** [worldbank/data-good-training#8]
**Describe the bug**
Depending on which World Bank Data Goods link is used, the are two different repositories on github for Nighttime Lights. 

This link https://worldbank.github.io/data-good-training/notebooks/nighttime-lights/nighttime-lights.html :

- After clicking on Nighttime Lights and going to the linked repository, it takes you to the worldbank/data-good-training repository.

This link https://datapartnership.org/gaza-israel-conflict-impact-analysis/notebooks/nighttime-lights/README.html : 

- After going to the linked repository, it takes you to the datapartnership/gaza-israel-conflict-impact-analysis repository.

Navigating the files in each of these repositories is different due to files being organized differently.
Screenshots of each github page attached.

<img width="1458" alt="gaza israel conflict impact analysis" src="https://github.com/worldbank/data-good-training/assets/149113579/4a52cf27-c279-437c-8d3f-bc861f108091">
<img width="1401" alt="data good training" src="https://github.com/worldbank/data-good-training/assets/149113579/2b1a9cd0-7efe-4768-8fae-9b84bcd88145">

**Comment by SahitiSarva** [comment]
@kholeigh -- This is a feature, not a bug. Could you please describe the issue you're having when looking at two separate repositories?
